---
- name: get app source
  unarchive:
    src: "{{ backend_src }}"
    dest: "{{ backend_extract_location }}"
    copy: no
  notify: restart grumpy

- name: create service
  copy:
    src: files/grumpy.service
    dest: "{{ backend_service_file }}"

- name: start service
  service:
    name: grumpy
    state: started
    enabled: true

- name: check
  uri:
    url: "{{ backend_check_url }}"
    status_code: 200
  when: backend_check_url is defined
