---
- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_packages }}"

- name: customize welcome message
  copy:
    content: hola 
    dest: /etc/motd
